### ISSUE TITLE
Entire extend of the deletion not highlighted in notebook

### ISSUE THREAD

**Issue by vkullu** [igvteam/igv-jupyter#36]
Hello,
I noticed when I loaded a VCF file from MANTA in the desktop version of IGV, it showed the nice deletion (several kbs) above HBA loci. However when I loaded the same in the jupter notebook, it shows a tick only at the start, but not the entire band over 60kb. Thank you very much for your help.

![Screen Shot 2020-07-02 at 10 05 20 PM](https://user-images.githubusercontent.com/6581358/86433872-b11daf00-bcb0-11ea-90e1-b69b9d95af63.png)

<img width="1143" alt="Screen Shot 2020-07-02 at 10 05 30 PM" src="https://user-images.githubusercontent.com/6581358/86433885-b67af980-bcb0-11ea-9d5f-0356091f5ce8.png">

**Comment by jrobinso** [comment]
If you can upload an example VCF that illustrates the problem I will look into it.   You can zip it and upload it here, or give me a URL where I can download it.

Also, what version of the Jupyter igv extension are you using?

**Comment by vkullu** [comment]
Thank you for your reply. These are customer VCFs so I am trying to figure out how to de-identify them within the company so I can share them.  How do I figure out my version of jupyter igv extension?

**Comment by jrobinso** [comment]
That's an excellent question, if you don't remember what you installed I'm
not sure.

The problem, if there is one, will be with "igv.js".   To see if its been
corrected since this jupyter release you can try loading your VCF at

https://igv.org/app

This is secure, igv.org/app runs in your browser nothing is uploaded.    If
it looks correct there the fix is to update the igv.js version your
notebook is using.  But first let's verify it.
